name: Upload AAB to Google Play

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AAB from release tag
        if: github.event.release != null
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.event.release.tag_name }}
          fileName: "localdesktop-*.aab"
          out-file-path: "target"
          extract: false

      - name: Download latest AAB (if manually triggered)
        if: github.event.release == null
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: "localdesktop-*.aab"
          out-file-path: "target"
          extract: false

      - name: Remove debug AABs
        run: rm -f target/*-debug.aab

      - name: Upload to Google Play (closed track)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: app.polarbear
          releaseFiles: target/*.aab
          track: alpha
