name: Upload AAB to Google Play

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download AAB from Release
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.event.release.tag_name }}
          fileName: "localdesktop-${{ steps.version.outputs.version }}.aab"
          out-file-path: "target"
          extract: false

      - name: Upload to Google Play (closed track)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: app.polarbear
          releaseFiles: target/*.aab
          track: closed
